# Generated by Django 5.1.6 on 2025-03-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseview',
            name='keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
